// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	api0 "github.com/enbility/eebus-go/api"
	"github.com/enbility/spine-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMaMDTInterface creates a new instance of MaMDTInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaMDTInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaMDTInterface {
	mock := &MaMDTInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MaMDTInterface is an autogenerated mock type for the MaMDTInterface type
type MaMDTInterface struct {
	mock.Mock
}

type MaMDTInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MaMDTInterface) EXPECT() *MaMDTInterface_Expecter {
	return &MaMDTInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) AddFeatures() {
	_mock.Called()
	return
}

// MaMDTInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type MaMDTInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *MaMDTInterface_Expecter) AddFeatures() *MaMDTInterface_AddFeatures_Call {
	return &MaMDTInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *MaMDTInterface_AddFeatures_Call) Run(run func()) *MaMDTInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MaMDTInterface_AddFeatures_Call) Return() *MaMDTInterface_AddFeatures_Call {
	_c.Call.Return()
	return _c
}

func (_c *MaMDTInterface_AddFeatures_Call) RunAndReturn(run func()) *MaMDTInterface_AddFeatures_Call {
	_c.Run(run)
	return _c
}

// AddUseCase provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) AddUseCase() {
	_mock.Called()
	return
}

// MaMDTInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type MaMDTInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *MaMDTInterface_Expecter) AddUseCase() *MaMDTInterface_AddUseCase_Call {
	return &MaMDTInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *MaMDTInterface_AddUseCase_Call) Run(run func()) *MaMDTInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MaMDTInterface_AddUseCase_Call) Return() *MaMDTInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MaMDTInterface_AddUseCase_Call) RunAndReturn(run func()) *MaMDTInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// MaMDTInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type MaMDTInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *MaMDTInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *MaMDTInterface_AvailableScenariosForEntity_Call {
	return &MaMDTInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *MaMDTInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *MaMDTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MaMDTInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *MaMDTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *MaMDTInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *MaMDTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MaMDTInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type MaMDTInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *MaMDTInterface_Expecter) IsCompatibleEntityType(entity interface{}) *MaMDTInterface_IsCompatibleEntityType_Call {
	return &MaMDTInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *MaMDTInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *MaMDTInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MaMDTInterface_IsCompatibleEntityType_Call) Return(b bool) *MaMDTInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MaMDTInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *MaMDTInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MaMDTInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type MaMDTInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *MaMDTInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *MaMDTInterface_IsScenarioAvailableAtEntity_Call {
	return &MaMDTInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *MaMDTInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *MaMDTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MaMDTInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *MaMDTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MaMDTInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *MaMDTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) RemoteEntitiesScenarios() []api0.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api0.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api0.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.RemoteEntityScenarios)
		}
	}
	return r0
}

// MaMDTInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type MaMDTInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *MaMDTInterface_Expecter) RemoteEntitiesScenarios() *MaMDTInterface_RemoteEntitiesScenarios_Call {
	return &MaMDTInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *MaMDTInterface_RemoteEntitiesScenarios_Call) Run(run func()) *MaMDTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MaMDTInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api0.RemoteEntityScenarios) *MaMDTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *MaMDTInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api0.RemoteEntityScenarios) *MaMDTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// MaMDTInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type MaMDTInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *MaMDTInterface_Expecter) RemoveUseCase() *MaMDTInterface_RemoveUseCase_Call {
	return &MaMDTInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *MaMDTInterface_RemoveUseCase_Call) Run(run func()) *MaMDTInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MaMDTInterface_RemoveUseCase_Call) Return() *MaMDTInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MaMDTInterface_RemoveUseCase_Call) RunAndReturn(run func()) *MaMDTInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// Temperature provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) Temperature(entity api.EntityRemoteInterface, unit model.UnitOfMeasurementType) (float64, error) {
	ret := _mock.Called(entity, unit)

	if len(ret) == 0 {
		panic("no return value specified for Temperature")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, model.UnitOfMeasurementType) (float64, error)); ok {
		return returnFunc(entity, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, model.UnitOfMeasurementType) float64); ok {
		r0 = returnFunc(entity, unit)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface, model.UnitOfMeasurementType) error); ok {
		r1 = returnFunc(entity, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MaMDTInterface_Temperature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Temperature'
type MaMDTInterface_Temperature_Call struct {
	*mock.Call
}

// Temperature is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - unit model.UnitOfMeasurementType
func (_e *MaMDTInterface_Expecter) Temperature(entity interface{}, unit interface{}) *MaMDTInterface_Temperature_Call {
	return &MaMDTInterface_Temperature_Call{Call: _e.mock.On("Temperature", entity, unit)}
}

func (_c *MaMDTInterface_Temperature_Call) Run(run func(entity api.EntityRemoteInterface, unit model.UnitOfMeasurementType)) *MaMDTInterface_Temperature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 model.UnitOfMeasurementType
		if args[1] != nil {
			arg1 = args[1].(model.UnitOfMeasurementType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MaMDTInterface_Temperature_Call) Return(f float64, err error) *MaMDTInterface_Temperature_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MaMDTInterface_Temperature_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, unit model.UnitOfMeasurementType) (float64, error)) *MaMDTInterface_Temperature_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type MaMDTInterface
func (_mock *MaMDTInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// MaMDTInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type MaMDTInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *MaMDTInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *MaMDTInterface_UpdateUseCaseAvailability_Call {
	return &MaMDTInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *MaMDTInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *MaMDTInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MaMDTInterface_UpdateUseCaseAvailability_Call) Return() *MaMDTInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *MaMDTInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *MaMDTInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}
